#!/bin/bash

# Run terraform destroy
if terraform destroy -auto-approve; 
then
    echo "Resources have been destroyed successfully."
else
    echo "Error: Resources could not be destroyed."
    exit 1
fi
